version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai_seller_postgres
    environment:
      POSTGRES_DB: ai_seller_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup_pgvector.sql:/docker-entrypoint-initdb.d/setup_pgvector.sql
    restart: unless-stopped

  backend:
    build: .
    container_name: ai_seller_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@postgres:5432/ai_seller_analysis
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ai_seller_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: 